### ISSUE TITLE
Support for fediverse services (Mastodon)

### ISSUE THREAD

**Issue by schulle4u** [GiovanniSalmeri/yellow-minishare#4]
In addition to centralized services it would be nice to have the fediverse (Mastodon as one of the most popular communities) as a sharing option. As services like Mastodon are decentrally organized, users need to enter their instance URL before sharing the actual content. So far the simplest solution I've found is [this jQuery-based library](https://github.com/Aly-ve/Mastodon-share-button), which even provides an option to remember the entered instance URL for next visit. Maybe you can build something better which doesn't require jQuery? 😀

**Comment by GiovanniSalmeri** [comment]
@schulle4u Well, my reply isn't exactely timely 😊. I am reviewing all my little extensions and I decided that minishare needed some refreshing, and so I have found the time also for considering Mastodon. After a little study I have found that the solution is easier than expected: I managed to do all in a handful of lines of Javascript (and no JQuery, of course 😄) and with some refactoring of the code (now services which need a variable field can be added just with a line more in PHP). Actually the JS code is now *smaller* than before, because after some tests I found that popups are nowadays just unreliable: a lot of people block them in their browser. So now one can choose between same page and new page (but no pop-up) and I have dropped the code for popup. Anyway: thank you for bringing my attention to Mastodon, I knew it only by name but it seems very interesting!

**Comment by schulle4u** [comment]
@GiovanniSalmeri no problem, good things take time 🙂 Many thanks, works great so far. However if `MinishareSamePage` is set to 1, for some reason in microsoft Edge and probably all Chromium-based Browsers I get a blocked popup warning after entering an instance. All other services work without this warning, although they tend to use the same code? Firefox causes no problems. If the used theme/markup is relevant to track down the issue, [use this blog](https://droidblind.de/blog/) as an example.

**Comment by GiovanniSalmeri** [comment]
Thank you very much for the feedback!

> I get a blocked popup warning after entering an instance

😭 It is the greatest problem with which I fought and I thought I managed to solve it... From what I have understood, the problem is a *philosophical* one: what is a popup? Is it 1. a new window with specified dimensions? or 2. a new window which is programmatically created (not by a direct user action), no matter what are its dimensions? In my tests, a generic Webkit (a good approximation for Safari) and Firefox follow the interpretation 1; Blink (tested with Vivaldi) follows interpretation 2. So in the end I managed to write a code in which, notwithstanding the Javascript-prompt which asks for the instance, a new window is created not programmatically, but simply as a delayed effect of the user click on the link: and this works well in all three my browsers. What you are saying unfortunately suggests that there is an even stricter interpretation: also a delayed effect can be considered a programmatic creation, and the "popup" gets blocked. But I do not understand the difference between Edge and Vivaldi, both of them are based on the same rendering engine. I will investigate the issue...

**Comment by GiovanniSalmeri** [comment]
@schulle4u Installed now Chromium. Same behaviour as Edge, unfortunately. Presently I see three possibilities:

+ leaving the things as they are. After all, one can always allow popups on a per-site basis
+ making the "new page" setting ineffective when there is a Javascript dialog (currently only in Mastodon)
+ suppressing the "new page" setting: all browsers have a way for manually triggering a new page (for example Ctrl+click, Ctrl+Enter) and this works well also for Mastodon (tested now). I remember the good old days of XHTML 1.0, when `target="_blank"` was outlawed 😁

Fourth possibility:

+ Opening a bug in Chrome / Edge and waiting 😁

What do you think about it?

**Comment by schulle4u** [comment]
@GiovanniSalmeri Probably we should save us from unnecessary headache and simply suppress the new page setting. I'm primarily a desktop user and still like this little extra comfort, but as you wrote above every browser has possibilities to manually trigger a new tab/window. So lets keep it simple and do it the Yellow way. 😀

**Comment by GiovanniSalmeri** [comment]
It seems very sensible to me. Let's follow the Yellow way! Thank you again for testing and suggesting The Right Thing to do.
